### PR TITLE
feat(parse-enum): improve enum parsing using json annotation for enum

### PR DESCRIPTION
**Pull request by billyandco**

### CODE REVIEW

**Comment by billyandco** [comment]
an enum doesnt need to have `toJson` and `fromJson` using the latest version
Retrofit is smart enough to create the right method in the right file

the actual solution you have doesn't work, because with fromJson, you cannot cast `json as Map<String, dynamic>`
and it should be better to use the library annotation for enum generation that will solve a lot of issues

image

image

image

image

image

**Comment by Sancene** [comment]
@billyandco 
```dart
@GET('student/curriculum')
  Future<void> getStudyPlan(
    @Query('order_enum') IOrderEnum orderEnum,
  );
```
This is what retrofit generates:
```dart
@override
  Future<void> getStudyPlan(orderEnum) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'order_enum': orderEnum.toJson()
    };
    final _headers = <String, dynamic>{};
    final Map<String, dynamic>? _data = null;
    await _dio.fetch<void>(_setStreamType<void>(Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
    )
        .compose(
          _dio.options,
          'student/curriculum',
          queryParameters: queryParameters,
          data: _data,
        )
        .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
  }
```
As you can see generated method uses toJson from orderEnum but it is not being generated by your method so it doesnt work.

The same is generated with your template: 

```
@override
  Future<void> getStudyPlan(IOrderEnum orderEnum) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'order_enum': orderEnum.toJson()
    };
    final _headers = <String, dynamic>{};
    final Map<String, dynamic>? _data = null;
    await _dio.fetch<void>(_setStreamType<void>(Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
    )
        .compose(
          _dio.options,
          'student/curriculum',
          queryParameters: queryParameters,
          data: _data,
        )
        .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
  }
```

**Comment by Carapacik** [comment]
Try to show your example and fill in the changes from the current branch

**Comment by billyandco** [comment]
in the case of `Result`, the json would look like (as example), `order` and `type` as IOrderEnum
```
{
  "order": "asc",
  "type": "desc",
}
```

Result will do
`ÌOrderEnum.fromJson(json['order'] as Map<String, dynamic>)`

but `json['order']` will not cast as a Map because the value is a String

**Comment by Carapacik** [comment]
I think error in retrofit_generator package, because retrofit gen for this request:
```dart
import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum IOrderEnum {
  asc,
  desc;
}
```

```dart
import 'package:dio/dio.dart';
import 'package:example/order.dart';
import 'package:retrofit/retrofit.dart';

part 'request.g.dart';

@RestApi()
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET('order')
  Future<IOrderEnum> getStudyPlan(@Query('order_enum') IOrderEnum orderEnum);
}
```

this code
```dart
Future<IOrderEnum> getStudyPlan(orderEnum) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'order_enum': orderEnum.toJson()
    };
    final _headers = <String, dynamic>{};
    final Map<String, dynamic>? _data = null;
    final _result = await _dio
        .fetch<Map<String, dynamic>>(_setStreamType<IOrderEnum>(Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
    )
            .compose(
              _dio.options,
              'order',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = IOrderEnum.fromJson(_result.data!);
    return value;
  }
```
And retrofit generate 
`final value = IOrderEnum.fromJson(_result.data!);`

**Comment by Carapacik** [comment]
I think you should replace Map<String, dynamic> to String
```
import 'package:json_annotation/json_annotation.dart';

enum IOrderEnum {
  asc,
  desc;

  const IOrderEnum();

  factory IOrderEnum.fromJson(String json) =>
      $enumDecode(_$IOrderEnumEnumMap, json);

  String toJson() => _$IOrderEnumEnumMap[this]!;
}

const _$IOrderEnumEnumMap = {IOrderEnum.asc: 'asc', IOrderEnum.desc: 'desc'};

void main() {
  final json = <String, String>{'order': 'asc'};
  print('Order: ${IOrderEnum.fromJson(json['order']!)}');
}
```

**Comment by billyandco** [comment]
Is it possible to add JsonEnum and JsonValue to this library to help retrofit and maybe avoid this retrofit generation error ?
it can be avoid in class generation also as i mentionned in the second comment

**Comment by Carapacik** [comment]
Then I think we should add the toJSON method there too. Or it will be generated using @JsonEnum()?

**Comment by Carapacik** [comment]
I think this is the best option:
```dart
import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum IOrderEnum {
  asc,
  desc;

  String toJson() => _$IOrderEnumEnumMap[this]!;
}

const _$IOrderEnumEnumMap = {
  IOrderEnum.asc: 'asc',
  IOrderEnum.desc: 'desc',
};
```
When the pull request is ready, tag me(Don't forget about the tests)

**Comment by billyandco** [comment]
Yeah that would be perfect, then the fromJson part is on retrofit side

and i would put JsonValue also for making sure that the name is camel case
```
@JsonValue('HELLO_WORLD')
helloWorld
```

Thank you very much ! do you want a PR ? or you wanna make that one ?

**Comment by Carapacik** [comment]
PR looks better

**Pull request closed without merging**
